server:
  port: 10264

spring:
  application:
    name: config-server
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
          clone-on-start: true
          default-label: main
          repos:
            auth:
              pattern:
                - 'auth-service'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - auth

            api:
              pattern:
                - 'shop-service'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - api

            eureka:
              pattern:
                - 'eureka'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - eureka

            batch:
              pattern:
                - 'ink3-batch'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - batch

            gateway:
              pattern:
                - 'gateway'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - gateway

            front:
              pattern:
                - 'front'
              uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
              search-paths:
                - front



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always