server:
  port: 10264

spring:
  application:
    name: config-server
  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: nhnacademy123!
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/nhnacademy-be09-ink3/ink3-config.git
          clone-on-start: true
          default-label: main
          repos:
            default:
              pattern:
                - 'auth-service'
              uri: https://github.com/your-repo/config-repo.git
              search-paths:
                - auth
          search-paths:
            - api
            - front
            - gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always